### ISSUE TITLE
toggle headers not working in Sphinx 2.0.1

### ISSUE THREAD

**Issue by skkirkham** [ulrobix/sphinxcontrib-contentui#2]
I am using python 3.6 and pip 19.0.6 on centos 7. I am having issues with the toggle headers functionality when using sphinx 2.0.1

```
mysphinx) [sharonk@ip-10-1-1-10 kogdocs]$ sphinx-build -b html source new_master
Running Sphinx v2.0.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 455 source files that are out of date
updating environment: 455 added, 0 changed, 0 removed
reading sources... [100%] 

...

The HTML pages are in new_master.

Exception occurred:
 File "mysphinx/lib/python3.6/site-packages/sphinxcontrib/contentui.py", line 90, in copy_assets
 app.info('Copying contentui stylesheet/javascript... ', nonl=True)
AttributeError: 'Sphinx' object has no attribute 'info'

```
The tabs look to be working fine but the toggle-headers are broken. 

My rst snippet looks like this

```
.. toggle-header::
    :header: **Example 2: Creating a python script environment on Kognitio**


    Other programs that have been installed on the system after the initial
    installation can also be used. A script environment to run python code
    can be created using::


        CREATE SCRIPT ENVIRONMENT python27
        COMMAND '/usr/local/bin/python2.7'


    Here Python 2.7 has already been installed on all nodes in the directory
    ``/usr/local/bin``. On Kognitio standalone this installation can be done
    easily using the Kognitio command utilities ``wxsync`` and ``wxtool``.

```
In the old version of Sphinx we use (1.6.3) this produces the following html snippet for the header

 `<p class="toggle-header" id="extscript-env-python"><strong>Example 2: Creating a python script environment on Kognitio</strong></p>
`
but with Sphinx (2.0.0) we are getting an extra paragraph that breaks the toggle-header:

```
<p class="toggle-header" id="extscript-env-python"><p><strong>Example 2: Creating a python script environment on Kognitio</strong></p>
> </p>
```

We also use the content tabs that are working fine.
Regards
Sharon

**Comment by ulrobix** [comment]
Thansk! 
Fixed

**Comment by skkirkham** [comment]
Hi Ulrobix.

Thanks for your quick response.

I downloaded the latest release. The error message has disappeared but my toggle-headers are still not working. The additional `<p>` is still in the html for the headers.

Regards
Sharon

**Comment by ulrobix** [comment]
sphinxcontrib-contentui  0.2.4 released. Please check
